name: Build and Push Docker image to GHCR

on:
  push:
    branches:
      - main  # or whichever branch you use

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write 

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}  

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest apps/financial-dashboard

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest